run:
  skip-dirs:
    - vendor

issues:
  max-per-linter: 999999
  max-same: 999999
  exclude:
    - composite literal uses unkeyed fields

linters-settings:
  unparam:
    algo: cha
    check-exported: false
  nakedret:
    max-func-lines: 0
  misspell:
    locale: US
  goconst:
    min-occurrences: 3
  gocyclo:
    min-complexity: 20
  lll:
    line-length: 120

linters:
  enable:
    - unconvert
    - gofmt
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - unparam
    - varcheck
    - deadcode
    - gosimple
    - gocyclo
    - nakedret
    - goconst
    - govet
    - megacheck
    - goimports
    - errcheck
    - golint
    - prealloc
    - lll
  disable:
